name: Scheduled GitHub Workflow

on:
  schedule:
    - cron: '54 22 * * *'  # Schedule to run at 11:45 PM UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print a message
        run: echo "Hello, GitHub Workflow!!"
