name: My First Workflow

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run a script
      run: echo "Hello, Littles Law!"
    - name: Print a message
      run: |
        CURRENT_HOUR=$(date -u '+%H')
        CURRENT_MINUTE=$(date -u '+%M')

          if [ "$CURRENT_HOUR" -eq 23 ] && [ "$CURRENT_MINUTE" -ge 45 ]; then
            echo "Current UTC time: $CURRENT_HOUR:$CURRENT_MINUTE"

