name: API Health Check

on:
  schedule:
    - cron: '45 23 * * *'  # Schedule to run at 11:45 PM UTC
  workflow_dispatch:

jobs:
  api_health_check:
    runs-on: ubuntu-latest

    steps:
      - name: Hit API and check response
        id: api_check
        run: |
          response=$(curl -s https://petstore.octoperf.com/actions/Caog.action?viewProduct=&productId=FI-SW-01)
          if [ -n "$response" ]; then
            echo "::set-output name=status::pass"
            echo "API is up and running"
          else
            echo "::set-output name=status::fail"
            echo "API is down or not responding"
            exit 1
          fi
